<?xml version="1.0" encoding="utf-8"?>
<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1392368034096" stop="1392368034106">
  <description>
&#1059; &#1101;&#1090;&#1086;&#1075;&#1086; &#1084;&#1086;&#1076;&#1091;&#1083;&#1103;, &#1082;&#1072;&#1082; &#1080; &#1091; &#1077;&#1075;&#1086; &#1090;&#1077;&#1089;&#1090;&#1086;&#1074;, &#1082;&#1080;&#1088;&#1080;&#1083;&#1083;&#1080;&#1095;&#1077;&#1089;&#1082;&#1080;&#1077; &#1086;&#1087;&#1080;&#1089;&#1072;&#1085;&#1080;&#1103;, &#1076;&#1072;&#1085;&#1085;&#1099;&#1077; &#1074; &#1102;&#1085;&#1080;&#1082;&#1086;&#1076;&#1077;

Created on Oct 19, 2013

@author: pupssman
</description>
  <name>demo.test_nonascii</name>
  <test-cases>
    <test-case severity="normal" start="1392368034097" status="passed" stop="1392368034097">
      <name>test_pass</name>
      <description>&#1069;&#1090;&#1086;&#1090; &#1090;&#1077;&#1089;&#1090; &#1087;&#1088;&#1086;&#1093;&#1086;&#1076;&#1080;&#1090;</description>
      <attachments/>
      <steps/>
    </test-case>
    <test-case severity="normal" start="1392368034099" status="failed" stop="1392368034099">
      <name>test_fail</name>
      <description>&#1069;&#1090;&#1086;&#1090; &#1090;&#1077;&#1089;&#1090; &#1087;&#1072;&#1076;&#1072;&#1077;&#1090;</description>
      <failure>
        <message>AssertionError: assert False</message>
        <stack-trace>def test_fail():
        u'&#1069;&#1090;&#1086;&#1090; &#1090;&#1077;&#1089;&#1090; &#1087;&#1072;&#1076;&#1072;&#1077;&#1090;'
    
&gt;       assert False
E       assert False

demo/test_nonascii.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <steps/>
    </test-case>
    <test-case severity="normal" start="1392368034104" status="failed" stop="1392368034104">
      <name>test_raise_cyrilling</name>
      <description>&#1069;&#1090;&#1086;&#1090; &#1090;&#1077;&#1089;&#1090; &#1074;&#1099;&#1082;&#1080;&#1076;&#1099;&#1074;&#1072;&#1077;&#1090; &#1080;&#1089;&#1082;&#1083;&#1102;&#1095;&#1077;&#1085;&#1080;&#1077; &#1089; &#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1084;&#1080; &#1073;&#1091;&#1082;&#1074;&#1072;&#1084;&#1080;</description>
      <failure>
        <message>Exception: &#1053;&#1077;&#1074;&#1077;&#1088;&#1086;&#1103;&#1090;&#1085;&#1072;&#1103; &#1087;&#1088;&#1086;&#1073;&#1083;&#1077;&#1084;&#1072;!</message>
        <stack-trace>def test_raise_cyrilling():
        u'&#1069;&#1090;&#1086;&#1090; &#1090;&#1077;&#1089;&#1090; &#1074;&#1099;&#1082;&#1080;&#1076;&#1099;&#1074;&#1072;&#1077;&#1090; &#1080;&#1089;&#1082;&#1083;&#1102;&#1095;&#1077;&#1085;&#1080;&#1077; &#1089; &#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1084;&#1080; &#1073;&#1091;&#1082;&#1074;&#1072;&#1084;&#1080;'
    
&gt;       raise Exception(u'&#1053;&#1077;&#1074;&#1077;&#1088;&#1086;&#1103;&#1090;&#1085;&#1072;&#1103; &#1087;&#1088;&#1086;&#1073;&#1083;&#1077;&#1084;&#1072;!')
E       Exception: &#1053;&#1077;&#1074;&#1077;&#1088;&#1086;&#1103;&#1090;&#1085;&#1072;&#1103; &#1087;&#1088;&#1086;&#1073;&#1083;&#1077;&#1084;&#1072;!

demo/test_nonascii.py:27: Exception</stack-trace>
      </failure>
      <attachments/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
